A magnetic $beta$ ray spectrometer is an instrument that is designed to analyze the energy distribution of $beta$ particles emitted from a radioactive source. This type of spectrometer utilizes the phenomena off deflection of charged radiation particle in a magnetic field to discern the energy of the particles that are encountered by a Geiger-Mueller counter - a radiation detector that is not sensitive to the energy information of the incident radiation particles.

The crucial components of the $beta$ partile spectrometer are -
+ Power Supply: This is utilized in constant current mode to drive current through a solenoidal coil.
+ Solenoidal coil: The current flowing through the coil creates an approximately uniform magnetic field, whose magnitude can be controlled by varying the current allowed to flow through the coil. The magnitude of the magnetic field can be calculated usin the following equation -
$
  B = mu n I
$
Where,
$B$ = Magnitude of the magnetic field.
$mu$ = Permeability of the material inside the solenoid.
$n$ = Number of turns in the solenoid per unit length of the solenoid.
$I$ = Current flowing through the solenoid.
+ Hall probe/Gaussmeter: It is used to measure the magnitude of the magnetic field present in the region where the $beta$ particles are present - using the Hall Effect. The Hall effect is a funamental phenomenon observed in conductors (and semiconductors) when theya re subjected to a magnetic field perpendicular to the direction of an eelectric current in the material. The effect of this is the generation of a transverve electric potential across the material, which is known as the Hall voltage. This is created due to the charge carriers in the material experiencing a transverse Lorentz force on them due to the magnetic field. This deflects the charge carries moving under the influence of the electric field to one side of the conductor. This accumulation of charges creates an electric field transverse to the original electric field that was present in the material, which manifests in the form of a measurable voltage difference. The Hall voltage can be calculated using the following expression - 
$
  V_H = (I B)/(q n d)
$
Where,
$V_H$ = Hall voltage
$I$ = Current flowing through the conductor (in Ampere)
$B$ = Magnitude of the magnetic field (in Tesla)
$q$ = charge of the carriers (in Coulomb)
$n$ = Number density of the charge carriers in the material
$d$ = Thickness of the conducting material.
If calibrated correctly, the Hall Voltage is proportional to the magnetic field strength, and can thus be used to measure the magnetic field that is generated by the solenoid.
+ Circular aperture with diaphrams: This is the piece on top of the solenoid, which holes to hold the Hall Probe, the radioactive source, and the Geiger-Mueller counter. The diaphrams present internally prevent the travel of any stray $beta$ particles from the source to the GM counter, except the particles that are travelling along a trajectory of a fixed radius.
+ Geiger-Mueller Counter: This is a widely used instrument for detecting and counting the number of ionizing radiation particles that are incident on it, including $beta$ rays. It consists of a cylindrial metal tude, a low pressure inert gas filling the tube, a quenching gas mixed in with the inert gas, and a central wire. The wall of the tube serves as the cathode, and the central wire works as the anode. A high voltage is applied between them. When a particle of ionizing radiation (a $beta$ particle in this case) enters the cyllindrical chamber, it collides with the gas atoms that are inside. This interaction causes the ionization of the gas atoms, creating a positive ion and a free secondary electron. These free electrons are then accelerated by the electric field created in the tube by the application of the high voltage, and they drift towards the central wire. They accelerate and gain enough energy to collide with and ionize other gas atoms along the way, creating an avalanche like process where more and more atoms are ionised and a great amplification of charge takes place. This phenomena is called Townshend Avalanching. These electrons are then picked up by the central wire, and the associated electronics detects the current pulse. Each such detected pulse is counted as the incidence of one charged particle on the GM counter. It is to be noted that unlike ion chambers or proportional counters, these avaalanches in the GM counters progress until a saturation level is reached - regardless of the energy oof the initial incident radiation that trigerred the events. In this process, the energy information of the incident radiation is lost entirely.

== Operating principle of the $beta$ spectrometer
When the radioactive material in the sourcee decays, it emits $beta$ particles of specific energies. These particles then travel into the annular top of the apparatus, where it is exposed to a magnetic field that is perpendicular to its direction of propagation in the plane. The $beta$ particles, which initially follow straight line trajectories, experience a Lorentz force given by -
$
  vec(F) = q (vec(v) times vec(B))
$
Where,
$vec(F)$ = Lorentz force
$vec(v)$ = Magnitude of the velocity of the $beta$ particle
$vec(B)$ = The magnetic field
This force causes the particles to now move in a circular trajectory as it like a centripetal force, and the radius of the trajectory is given by - 
$
  R = p / (e B)
$
Where,
$R$ = Radius of the trajectory
$p$ = Momentum of the $beta$ particle
$e$ = Charge of the particle
$B$ = Magnitude of the magnetic field
Due to the presence of the diaphrams in the annulus, all $beta$ particles except the ones present on trajectory of a predetermined radius are stopped from approaching the wwindow of the GM counter. The GM counter is then used to count the number of particles that are incident over a fixed time period.
Since the radius is fixed by the geometry of the equipment, $p prop B$. Thus, by varying the current through the coil and measuring the magnitude of the magnetic field using the Hall probe, we can determine the energy of the $beta$ particles that can reach the GM counter. We count the number of such particles arriving at the counter, and we use this information to form the spectra of the sources.